 export const diseaseSettings= (weight)  =>( {
    ARDS: {
      name: "سندرم زجر تنفسی حاد",
      description: "PEEP بالا، حجم جاری پایین (4-6 cc/kg)، RR بالا",
      settings: {
        tidalVolume: (weight * 5).toFixed(1),
        respiratoryRate: 40,
        peep: 8,
        fio2: 50,
        pip: 22,
        ieRatio: "1:2",
        flowRate: 60,
        mode: "SIMV",
        pressureSupport: 10,
        
        ti: 1.0,
        trigger: 5,
      },
    },
    Pneumonia: {
      name: "پنومونی",
      description: "PEEP بالا، حجم جاری پایین (4-6 cc/kg)، RR بالا",
      settings: {
        tidalVolume: (weight * 5).toFixed(1),
        respiratoryRate: 40,
        peep: 8,
        fio2: 50,
        pip: 22,
        ieRatio: "1:2",
        flowRate: 60,
        mode: "SIMV",
        pressureSupport: 10,
       
        ti: 1.0,
        trigger: 5,
      },
    },
    Asthma: {
      name: "آسم",
      description: "PEEP پایین، حجم جاری پایین، RR بالا",
      settings: {
        tidalVolume: (weight * 5).toFixed(1),
        respiratoryRate: 38,
        peep: 3,
        fio2: 40,
        pip: 16,
        ieRatio: "1:3",
        flowRate: 70,
        mode: "SIMV",
        pressureSupport: 12,
        
        ti: 1.2,
        trigger: 5,
      },
    },
    Bronchiolitis: {
      name: "برونشیولیت",
      description: "PEEP پایین، حجم جاری پایین، RR بالا",
      settings: {
        tidalVolume: (weight * 5).toFixed(1),
        respiratoryRate: 38,
        peep: 3,
        fio2: 40,
        pip: 16,
        ieRatio: "1:3",
        flowRate: 70,
        mode: "SIMV",
        pressureSupport: 12,
       
        ti: 1.2,
        trigger: 5,
      },
    },
    RDS: {
      name: "سندرم زجر تنفسی نوزادان",
      description: "تنظیمات ویژه نوزادان با RDS",
      settings: {
        tidalVolume: (weight * 5).toFixed(1),
        respiratoryRate: 45,
        peep: 6,
        fio2: 45,
        pip: 20,
        ieRatio: "1:2",
        flowRate: 50,
        mode: "SIMV",
        pressureSupport: 8,
      
        ti: 0.8,
        trigger: 5,
      },
    },
    COPD: {
      name: "بیماری انسدادی مزمن ریوی",
      description: "RR پایین، نسبت I:E طولانی",
      settings: {
        tidalVolume: (weight * 6).toFixed(1),
        respiratoryRate: 20,
        peep: 4,
        fio2: 35,
        pip: 18,
        ieRatio: "1:3",
        flowRate: 55,
        mode: "SIMV",
        pressureSupport: 15,
        
        ti: 1.5,
        trigger: 5,
      },
    },
    LOC: {
      name: "کاهش سطح هوشیاری",
      description: "تنظیمات استاندارد برای بیماران با کاهش سطح هوشیاری",
      settings: {
        tidalVolume: (weight * 6).toFixed(1),
        respiratoryRate: 35,
        peep: 5,
        fio2: 40,
        pip: 18,
        ieRatio: "1:2",
        flowRate: 60,
        mode: "SIMV",
        pressureSupport: 10,
        
        ti: 1.0,
        trigger: 5,
      },
    },
    Other: {
      name: "سایر بیماری‌ها",
      description: "تنظیمات استاندارد ونتیلاتور",
      settings: {
        tidalVolume: (weight * 6).toFixed(1),
        respiratoryRate: 35,
        peep: 5,
        fio2: 40,
        pip: 18,
        ieRatio: "1:2",
        flowRate: 60,
        mode: "SIMV",
        pressureSupport: 10,
        
        ti: 1.0,
        trigger: 5,
      },
    },
  });

